default: &default
  store_options:
    max_size: 268435456  # 256MB
    namespace: development

development:
  <<: *default
  store_options:
    namespace: development

test:
  <<: *default
  store_options:
    namespace: test

production:
  <<: *default
  database: cache
  store_options:
    namespace: production