
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # Use template0 to avoid encoding conflicts and force UTF-8
  template: template0

development:
  <<: *default
  database: bms_development

test:
  <<: *default
  database: bms_test

production:
  <<: *default
  database: bms_production
  url: <%= ENV["DATABASE_URL"] %>