
default: &default
  adapter: postgresql
  encoding: LATIN1
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # Use template0 to avoid encoding conflicts and force UTF-8
  template: template0

development:
  <<: *default
  database: bms_development

test:
  <<: *default
  database: bms_test

production:
  primary:
    <<: *default
    database: bms_production
    url: <%= ENV["DATABASE_URL"] %>
  cable:
    <<: *default
    database: bms_production
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cable_migrate
  queue:
    <<: *default
    database: bms_production
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/queue_migrate
  cache:
    <<: *default
    database: bms_production
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cache_migrate